// <auto-generated />
using System;
using Assignment_03_EFCore.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_03_EFCore.Migrations
{
    [DbContext(typeof(ItiDbContext))]
    [Migration("20250303225554_CreateCourseAndTopicTables And RelationShipBetweenCourseAndTopic")]
    partial class CreateCourseAndTopicTablesAndRelationShipBetweenCourseAndTopic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment_03_EFCore.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 10L, 10);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ToPicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToPicId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 10L, 10);

                    b.Property<DateOnly?>("HiringDate")
                        .HasColumnType("date");

                    b.Property<int?>("InsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InsId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Bouns")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int?>("DepId")
                        .HasColumnType("int");

                    b.Property<double?>("HourRate")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("DepId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FName");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LName");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Course", b =>
                {
                    b.HasOne("Assignment_03_EFCore.Models.Topic", "Topic")
                        .WithMany("Courses")
                        .HasForeignKey("ToPicId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Department", b =>
                {
                    b.HasOne("Assignment_03_EFCore.Models.Instructor", "Instructor")
                        .WithMany("Departments")
                        .HasForeignKey("InsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Instructor", b =>
                {
                    b.HasOne("Assignment_03_EFCore.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Student", b =>
                {
                    b.HasOne("Assignment_03_EFCore.Models.Department", "StudentDepartments")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("StudentDepartments");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Instructor", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Assignment_03_EFCore.Models.Topic", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
